from analisador.sintatico.Production import Production

productions = [
    Production("P'", [ "P" ]),
    Production("P", [ "inicio",  "V", "A" ]),
    Production("V", [ "varinicio",  "LV" ]),
    Production("LV", [ "D",  "LV" ]),
    Production("LV", [ "varfim",  "pt_v" ]),
    Production("D", [ "TIPO",  "L", "pt_v" ]),
    Production("L", [ "id",  "vir", "L" ]),
    Production("L", [ "id" ]),
    Production("TIPO", [ "inteiro"  ]),
    Production("TIPO", [ "real"  ]),
    Production("TIPO", [ "literal"  ]),
    Production("A", [ "ES",  "A" ]),
    Production("ES", [ "leia",  "id", "pt_v" ]),
    Production("ES", [ "escreva",  "ARG", "pt_v" ]),
    Production("ARG", [ "lit" ]),
    Production("ARG", [ "num" ]),
    Production("ARG", [ "id" ]),
    Production("A", [ "CMD", "A" ]),
    Production("CMD", [ "id", "atr", "LD", "pt_v" ]),
    Production("LD", [ "OPRD", "opm", "OPRD" ]),
    Production("LD", [ "OPRD" ]),
    Production("OPRD", [ "id"  ]),
    Production("OPRD", [ "num" ]),
    Production("A", [ "COND",  "A" ]),
    Production("COND", [ "CAB",  "CP" ]),
    Production("CAB", [ "se",  "ab_p", "EXP_R", "fc_p", "entao" ]),
    Production("EXP_R", [ "OPRD",  "opr", "OPRD" ]),
    Production("CP", [ "ES",  "CP" ]),
    Production("CP", [ "CMD",  "CP" ]),
    Production("CP", [ "COND",  "CP" ]),
    Production("CP", [ "fimse" ]),
    Production("A", [ "R",  "A" ]),
    Production("R", [ "CABR",  "CPR" ]),
    Production("CABR", [ "repita",  "ab_p", "EXP_R", "fc_p" ]),
    Production("CPR", [ "ES",  "CPR" ]),
    Production("CPR", [ "CMD",  "CPR" ]),
    Production("CPR", [ "COND",  "CPR" ]),
    Production("CPR", [ "fimrepita" ]),
    Production("A", [ "fim" ])
]

friendly_names = {
    "OPM": "operador matemático",
    "ATR": "atribuição",
    "FC_P": "fecha parênteses",
    "VIR": "vírgula",
    "EOF": "fim de arquivo",
    "ID": "identificador",
    "NUM": "número",
    "LIT": "literal",
    "AB_P": "abre parênteses",
    "OPR": "operador relacional",
    "PT_V": "ponto e vírgula"
}
